ERROR - 2022-03-22 00:09:51 --> Error connecting to the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

CRITICAL - 2022-03-22 00:09:51 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-22 00:11:10 --> Error connecting to the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

CRITICAL - 2022-03-22 00:11:10 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-22 00:11:52 --> Error connecting to the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

CRITICAL - 2022-03-22 00:11:52 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-22 00:34:06 --> Error connecting to the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

CRITICAL - 2022-03-22 00:34:06 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-22 00:37:39 --> Error connecting to the database: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

CRITICAL - 2022-03-22 00:37:39 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-22 00:38:47 --> Error connecting to the database: Access denied for user '****'@'192.168.1.68' (using password: YES)
CRITICAL - 2022-03-22 00:38:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'192.168.1.68' (using password: YES)
#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2022-03-22 00:38:49 --> Error connecting to the database: Access denied for user '****'@'192.168.1.68' (using password: YES)
CRITICAL - 2022-03-22 00:38:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'192.168.1.68' (using password: YES)
#0 C:\laragon\www\vet\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\laragon\www\vet\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\laragon\www\vet\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\laragon\www\vet\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\laragon\www\vet\app\Controllers\Usuario.php(14): CodeIgniter\BaseModel->findAll()
#5 C:\laragon\www\vet\system\CodeIgniter.php(832): App\Controllers\Usuario->index()
#6 C:\laragon\www\vet\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\laragon\www\vet\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\vet\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
